name: Build & Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ["20"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies with NPM
        run: |
          npm i -g @vercel/ncc
          npm install

      - name: Build new release
        run: ncc build index.js --license licenses.txt

      - name: Open pull request with changes
        uses: peter-evans/create-pull-request@v6
        with:
          title: New build
          branch: auto-build
          delete-branch: true
