name: Build & Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Lint/Build/Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ["20"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm i -g npm@latest
      - run: npm i -g @vercel/ncc
      - run: npm ncc build index.js --license licenses.txt
      - run: npm test
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: New build
          branch: auto-build
          delete-branch: true
